# Generated by Django 3.2.18 on 2023-04-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artGalleryMain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artgalleryusers',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artgalleryusers',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
