# Generated by Django 3.2.18 on 2023-04-01 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artGalleryMain', '0002_auto_20230401_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='art')),
                ('price', models.FloatField()),
                ('style', models.CharField(choices=[('FINE_ART', 'Fine Art'), ('ABSTRACT', 'Abstract'), ('MODERN', 'Modern'), ('STREET_ART', 'Street Art'), ('POP_ART', 'Pop Art')], max_length=100)),
                ('medium', models.CharField(choices=[('OIL', 'Oil'), ('WATER_COLOUR', 'Water Colour'), ('AIR_BRUSH', 'Air Brush'), ('ACRYLIC', 'Acrylic'), ('DIGITAL', 'Digital')], max_length=100)),
                ('subject', models.CharField(choices=[('POTRAIT', 'Potrait'), ('LANDSCAPE', 'Landscape'), ('STILL_LIFE', 'Still Life'), ('NATURE', 'Nature'), ('BEACH', 'Beach')], max_length=100)),
                ('category', models.CharField(choices=[('PAINTING', 'Painting'), ('DEGITIAL_ART', 'Degitial Art'), ('PHOTOGRAPHY', 'Photography'), ('SCULPTURE', 'Sculpture'), ('PRINTS', 'Prints'), ('DRAWING', 'Drawing')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
