# Generated by Django 3.2.18 on 2023-04-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artGalleryMain', '0003_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
