# Generated by Django 3.2.18 on 2023-05-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artGalleryMain', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled'), ('PENDING', 'Pending')], default='PENDING', max_length=100),
        ),
    ]
