# Generated by Django 3.2.18 on 2023-05-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artGalleryMain', '0007_auto_20230503_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='shipping_fee',
            field=models.FloatField(default=10.0),
        ),
    ]
