# Generated by Django 3.2.18 on 2023-05-03 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artGalleryMain', '0008_art_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='category',
            field=models.CharField(choices=[('PAINTING', 'Painting'), ('DEGITIAL_ART', 'Digital Art'), ('PHOTOGRAPHY', 'Photography'), ('SCULPTURE', 'Sculpture'), ('PRINTS', 'Prints'), ('DRAWING', 'Drawing')], max_length=100),
        ),
        migrations.CreateModel(
            name='wishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artGalleryMain.art')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
