# Generated by Django 3.2.18 on 2023-05-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artGalleryMain', '0009_auto_20230503_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artgalleryusers',
            options={},
        ),
    ]
