# Generated by Django 3.2.18 on 2023-05-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artGalleryMain', '0011_auto_20230504_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artgalleryusers',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='artgalleryusers',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
