# Generated by Django 3.2.18 on 2023-05-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artGalleryMain', '0018_remove_cart_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageposter',
            name='isLastItem',
            field=models.BooleanField(default=False),
        ),
    ]
