# Generated by Django 4.2.1 on 2023-05-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artGalleryMain", "0019_homepageposter_islastitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("image", models.ImageField(upload_to="blog")),
                ("description", models.TextField()),
                (
                    "blog_category",
                    models.CharField(
                        choices=[
                            ("PAINTING", "Painting"),
                            ("DEGITIAL_ART", "Digital Art"),
                            ("PHOTOGRAPHY", "Photography"),
                            ("SCULPTURE", "Sculpture"),
                            ("PRINTS", "Prints"),
                            ("DRAWING", "Drawing"),
                        ],
                        default="PAINTING",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("quote", models.CharField(max_length=500)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
