"""
Django settings for artGallery project.

Generated by 'django-admin startproject' using Django 3.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f85em&381@(^3kfnyfi43a3&h$(g8ju2t$gg+tk#0_nbsz99f3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
if DEBUG == True:
    ALLOWED_HOSTS = [
        "artista.localhost:8000",
        "artist.localhost:8000",
        "artistaapi.localhost:8000",
        "*",
    ]
else:
    ALLOWED_HOSTS = [
        "artistaapi.lunatech.pk",
        "artist.lunatech.pk",
        "artista.lunatech.pk"
    ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "adminArtist.apps.AdminartistConfig",
    "artGalleryApp.apps.ArtgalleryappConfig",
    "artGalleryMain.apps.ArtgallerymainConfig",
    'django_hosts',
    "corsheaders",
    'rest_framework.authtoken',

]
AUTH_USER_MODEL = "artGalleryMain.ArtGalleryUsers"
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        'rest_framework.authentication.TokenAuthentication',
    ),
    "DEFAULT_PAGINATION_CLASS": "artGalleryApp.other.pagination.StandardResultsSetPagination",

}
MIDDLEWARE = [
    'django_hosts.middleware.HostsRequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'artGallery.urls'
ROOT_HOSTCONF = 'artGallery.hosts'
DEFAULT_HOST = 'www'
if DEBUG == True:
    PARENT_HOST = '.localhost:8000'
else:
    PARENT_HOST = '.lunatech.pk'
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",

]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                "authextra": "artGalleryMain.templatetags.authextra"
            }

        },
    },
]

WSGI_APPLICATION = 'artGallery.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

if DEBUG == False:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'artista',
            'USER': 'lunagym',
            'PASSWORD': 'gym@1218',
            'HOST': 'localhost',
            'PORT': '',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# LOGIN_REDIRECT_URL = '../login/"'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "mail.electricemus.com"
EMAIL_PORT = 465
EMAIL_HOST_USER = "muzamil@electricemus.com"
EMAIL_HOST_PASSWORD = "Pakistan@112233"
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = 'muzamil@electricemus.com'
PASSWORD_RESET_TIMEOUT = 3000
